---
language: shell

env:
  - IMAGE_NAME="${DOCKER_ORG}/geospaas"

services: docker
if: 'type = push'

# Environment variables defined as part of the Travis CI repository configuration are:
# - GITHUB_API_TOKEN: Github API key for the nerscci user

install:
  - docker pull $IMAGE_NAME || true
  - docker build --cache-from $IMAGE_NAME . -t ${DOCKER_ORG}/geospaas_api

script:
  - docker run --rm -v "$(pwd):/src" ${DOCKER_ORG}/geospaas_api python setup.py sdist bdist_wheel runtests.py

# If the build is triggered by a tag and an API token is defined for the branch
# (in the travis repository settings), a package is built and added to the release
deploy:
  on:
    tags: true
    condition: -n "${GITHUB_API_TOKEN}"
  provider: releases
  api_key: "${GITHUB_API_TOKEN}"
  file: 'dist/*'
  file_glob: true
  skip_cleanup: true
...