---
language: shell

env:
  - IMAGE_NAME="${DOCKER_ORG}/geospaas_api"

services: docker
if: 'type = push'

# Environment variables defined as part of the Travis CI repository configuration are:
# - GITHUB_API_TOKEN: Github API key for the nerscci user

install:
  - docker build . -t $IMAGE_NAME

script:
  - >
    docker run --rm
    -e "TRAVIS=true"
    -e TRAVIS_JOB_ID
    -e TRAVIS_BRANCH
    -e TRAVIS_PULL_REQUEST
    -v "$(pwd):/src"
    $IMAGE_NAME
    bash -c "source /opt/conda/bin/activate && coverage run runtests.py && coveralls"

# If the build is triggered by a tag and an API token is defined for the branch
# (in the travis repository settings), a package is built and added to the release
#-e COVERALLS_REPO_TOKEN
#
deploy:
  on:
    tags: true
    condition: -n "${GITHUB_API_TOKEN}"
  provider: releases
  api_key: "${GITHUB_API_TOKEN}"
  file: 'dist/*'
  file_glob: true
  skip_cleanup: true
...